services:
  strapi:
    container_name: strapi
    build:
      context: ./cms
      dockerfile: Dockerfile
    image: strapi:latest
    restart: always
    env_file:
      - ./cms/.env
    environment:
      NODE_ENV: production
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - 127.0.0.1:1337:1337
    networks:
      - strapi
    depends_on:
      strapiDB:
        condition: service_healthy

  strapiDB:
    container_name: strapiDB
    restart: always
    image: postgres:16-alpine
    env_file:
      - ./cms/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    # в прод не открывать порт + в env DATABASE_HOST должен быть strapiDB
    # ports:
    #   - 5432:5432
    networks:
      - strapi
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_YANDEX_API_KEY=${NEXT_PUBLIC_YANDEX_API_KEY}
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    depends_on:
      strapi:
        condition: service_healthy
    networks:
      - strapi

volumes:
  strapi-data:
  strapi-uploads:

networks:
  strapi:
    name: strapi
    driver: bridge
